publish:
  image: clickable/ci-16.04-armhf
  only:
    - tags
  script:
    - clickable -c platforms/ubuntu_touch/clickable.json clean build review
    - clickable -c platforms/ubuntu_touch/clickable.json publish "$CI_COMMIT_MESSAGE"
  artifacts:
    paths:
      - build/*/app/*.click
    expire_in: 1 week

build:
  image: clickable/ci-16.04-armhf
  except:
    - tags
  script:
    - clickable -c platforms/ubuntu_touch/clickable.json clean build review
  artifacts:
    paths:
      - build/*/app/*.click
    expire_in: 1 week
